- name: Init Kubernetes cluster
  shell: |
          kubeadm init --pod-network-cidr 192.168.0.0/16 \
          --token {{ kube_token }}
  register: init_cluster

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ".kube/config"
    owner: ubuntu
    group: ubuntu
    mode: 0755
    remote_src: yes

- name: Pass bridged IPv4 Traffic to iptables chains
  shell: |
          echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf && sysctl -p
  register: traffic_config


