# demo_setup.yml
- name: Provision Kubernetes Workers - EC2
  ec2:
    aws_access_key: "{{ awskey }}"
    aws_secret_key: "{{ awssecretkey }}"
    group: dw-sec-group
    keypair: dwelc
    instance_type: t2.medium
    image: ami-07dc734dc14746eab # Ubuntu 18.04 LTS
    exact_count: "{{ worker_replicas }}"
    region: eu-west-2 # London
    vpc_subnet_id: subnet-10594e68
    wait: yes
    volumes:
      - device_name: /dev/sdb
        volume_type: standard
        volume_size: 20
    count_tag:
        Name: dw-k8-worker
    instance_tags:
        Name: dw-k8-worker
        Owner: "{{ owner }}"
        Cluster: dw-k8-cluster
    assign_public_ip: yes
  register: ec2workers

- name: Wait for SSH to come up - Workers
  local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                state=started
  with_items: "{{ ec2workers.instances }}"

#- debug: var=ec2workers
#- debug: var=ec2workers.instances
#- debug: var=ec2workers.instances[0].public_ip

- name: Add the Workers to hosts file
  local_action: lineinfile
                path=/Users/dan/Documents/repos/ansible-prototypes/hosts
                regexp={{ item.public_ip }} 
                insertafter="[workers]+" line={{ item.public_ip }}
  with_items: "{{ ec2workers.instances }}"

- name : Add Worker hosts to inventory
  local_action: add_host
                hostname={{ item.public_ip }}
                groups=workers
  with_items: "{{ ec2workers.instances }}"

- name: Provision a Kubernetes Master - EC2
  ec2:
    aws_access_key: "{{ awskey }}"
    aws_secret_key: "{{ awssecretkey }}"
    group: dw-sec-group
    keypair: dwelc
    instance_type: t2.medium
    image: ami-07dc734dc14746eab # Ubuntu 18.04 LTS
    wait: true
    exact_count: "{{ master_replicas }}"
    region: eu-west-2 # London
    vpc_subnet_id: subnet-10594e68
    volumes:
      - device_name: /dev/sdb
        volume_type: standard
        volume_size: 20
    count_tag:
        Name: dw-k8-master
    instance_tags:
        Name: dw-k8-master
        Owner: "{{ owner }}"
        Cluster: "{{ cluster_name }}"
    assign_public_ip: yes
  register: ec2masters

- name: Wait for SSH to come up
  local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                state=started
  with_items: "{{ ec2masters.instances }}"

- name: Add the Masters to hosts file
  local_action: lineinfile
                path=/Users/dan/Documents/repos/ansible-prototypes/hosts
                regexp={{ item.public_ip }} 
                insertafter='^\[masters\]' line={{ item.public_ip }}
  with_items: "{{ ec2masters.instances }}"

- name : Add Master hosts to inventory
  local_action: add_host
                hostname={{ item.public_ip }}
                groups=masters
  with_items: "{{ ec2masters.instances }}"