- name: Init Kubernetes cluster
  hosts: masters
  shell: |
    kubeadm init --pod-network-cidr 10.244.0.0/16 /
                 --token {{ kube_token }}
  register: init_cluster

- name: Join Workers To cluster
  hosts: Workers
  shell: |
    kubeadm join --token {{ kube_token }} \
                 --discovery-token-unsafe-skip-ca-verification \
                 {{ ec2masters.instances[0].public_ip }}:6443



