- name: Docker - Add Repo GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker - Add Repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: yes

- name: Docker - Install Docker CE
  apt:
    name: docker-ce
    state: present

- name: Docker - Prevent Packages Auto-Upgrading
  command: apt-mark hold docker-ce


- name: Kubernetes - Add Repo GPG Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Kubernetes - Add Repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: yes

- name: Kubernetes - Install Kubeadm, Kubelet, Kubectl
  apt:
    name:
      - kubectl
      - kubeadm
      - kubelet
    state: present

- name: Kubernetes - Prevent Packages Auto-Upgrading
  command: apt-mark hold kubelet kubeadm kubectl